### ISSUE TITLE
numerical derivation gives inaccurate result

### ISSUE THREAD

**Issue by Michael-63** [YvanTT/arTIfiCE#2]
### Describe the bug clearly: what happens: crash? reset? freeze? ...
the numerical derivation of the following expression gives an inaccurate result.

### How to reproduce the bug
when trying to find the first derivative of the function f(x)=-5/27x^3+5/6x^2 at the point x=1.
1. enter the following expression "nDeriv(-(5/27)x^3+5/6x^2,x,1)  you will get as result 1.11111092592 and not the correct result 10/9 or 1.11111...
2. the same ressult in classic mode.
3. the specification of an epsilon value can't prescribe the result.

Maybe I'm wrong, but I wasn't able to get a more accurate result. I am a little bit surprised that it shouldn't be possible to get the exact result. Other calculators have no problems with the calculation of this arithmetic expression.

Many thanks,
--Michael--

### Calculator version
This is the most important part:
- **Which calculator model exactly:**
**TI-84 Plus CE-T Python Edition**
(it must be one of the following: TI-83 Premium CE, TI-83 Premium CE Edition Python, TI-84 Plus CE, TI-84 Plus CE-T, TI-84 Plus CE-T Python Edition)

- **Which Boot and OS versions is the calculator running:**
**Boot: 5.5.0.0006** ; **OS: 5.6.0.0020**
(To know: turn on your calc, go to the home screen (where you do calculations), then press <kbd>mode</kbd> then <kbd>alpha</kbd> then <kbd>ln</kbd>. Get the two version numbers (for instance 5.0.0.0089 and 5.6.0.0020), then press <kbd>on</kbd> to return to the home screen.)

- **Which hardware revision is your calculator:**
**L-0720P**
(On the back of the calculator, in the middle towards the top, there are some characters, that may looks like a serial number: if there are two parts (serial numbers on the left, and some characters on the right, type here those characters on the right which should look like `L-0620P`. Otherwise, type down the serial number, it can look like `B06402A57`)
_This information is useful to know what TI changed in the hardware over time (it indicates where and where the calculator was manufactured, and the hardware revision letter), and helps tracking down the issue._

- **Approximately when did you buy the calculator:**
**Feb. 2021**
(Optional, this also helps to know when some versions came out in order to track changes over time)

### Additional info / Screenshots / Video
Add any other info that could help understand the problem

**Comment by commandblockguy** [comment]
This repo is for the arTIfiCE jailbreak - this issue is part of the calculator's OS and completely unrelated to arTIfiCE, so there's nothing the developer of this repo can do about it.

`nDeriv(` uses numeric differentiation, rather than symbolic integration. Basically, rather than solving the integral and then plugging in the correct value, it looks at a small section of the function and calculates rise/run. This method is fundamentally an approximation, and therefore can't give an exact result for the integral. An exact result would require the calculator to solve the integral, which would require a computer algebra system, which just isn't present on the 84+ series.

**Comment by YvanTT** [comment]
Indeed, thanks @commandblockguy !
