### ISSUE TITLE
Python Shell Freezes

### ISSUE THREAD

**Issue by Cybernite21** [YvanTT/arTIfiCE#6]
### Describe the bug clearly:

After I jailbreak and get cesium and use the python program, the shell freezes once the program finishes running. I can see it doing things like icons for 2nd and alpha and the spinning circle, but the ram is completely taken up. I did reset and resend os files and python works fine without the jailbreak and cesium. But I want this to work right with the jailbreak.

### How to reproduce the bug
1. Jailbreak
2. Get Cesium
3. go to python app
4. run any program

### Calculator version
TI-84 Plus CE-T Python Edition

- **Which Boot and OS versions is the calculator running:**
**Boot: 5.6.1.0006** ; **OS: 5.7.0.0017**

- **Which hardware revision is your calculator:**
**84PLCE**

- **Approximately when did you buy the calculator:**
**4/9/2022**

**Comment by adriweb** [comment]
I'll let other people confirm this, I guess, but if you managed to launch the Cesium installer (and install Cesium) that means arTIfiCE worked correctly in the first place, so you should:
1. Make sure you use the very latest Cesium version
2. Report the issue on the Cesium side and not here, since arTIfiCE itself worked fine after all. 

By the way, your hardware revision should just be a letter, next to the serial on the back. The whole datecode containing that letter is useful for documentation purposes anyway. It should look like L-0921T.

**Comment by YvanTT** [comment]
Yes make sure to download the latest version of the tools, thanks @adriweb !
